





exco_platform_view:
    path:    /advert/{id}
    defaults:
        _controller: EXCOPlatformBundle:Advert:view
    requirements:
        id: \d+


exco_platform_add:
    path:    /add
    defaults:
        _controller: EXCOPlatformBundle:Advert:add

exco_platform_edit:
   path:    /edit/{id}
   defaults:
       _controller: EXCOPlatformBundle:Advert:edit
   requirements:
       id: \d+

exco_platform_delete:
       path:    /delete/{id}
       defaults:
           _controller: EXCOPlatformBundle:Advert:delete
       requirements:
           id: \d+

exco_platform_home:
    path:    /{page}
    defaults:
        _controller: EXCOPlatformBundle:Advert:index
        page:       1
        requirements:
            page: \d*

exco_platform_purge:
    path:     /purge/{days}
    defaults:
        _controller: EXCOPlatformBundle:Advert:purge
    requirements:
        days: \d+


