
services:
  exco_platform.antispam:
      class: EXCO\PlatformBundle\Antispam\OCAntispam
      arguments:
          - "@mailer"
          - %locale%
          - 50

  exco_platform.email.application_mailer:
      class: EXCO\PlatformBundle\Email\ApplicationMailer
      arguments:
          - "@mailer"

  exco_platform.doctrine_listener.application_creation:
    class: EXCO\PlatformBundle\DoctrineListener\ApplicationCreationListener
    arguments:
      - "@exco_platform.email.application_mailer"
    tags:
      - { name: doctrine.event_listener, event: postPersist }

  exco_platform.purger.advert:
      class: EXCO\PlatformBundle\Purger\AdvertPurger
      arguments:
        - "@doctrine.orm.entity_manager"