<!doctype html>

<html lang="fr">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="A front-end template that helps you build fast, modern mobile web apps.">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0">
    <title>Blog</title>

    <!-- Add to homescreen for Chrome on Android -->
    <meta name="mobile-web-app-capable" content="yes">
    <link rel="icon" sizes="192x192" href="assets/images/android-desktop.png">

    <!-- Add to homescreen for Safari on iOS -->
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="apple-mobile-web-app-title" content="Material Design Lite">
    <link rel="apple-touch-icon-precomposed" href="assets/images/ios-desktop.png">

    <!-- Tile icon for Win8 (144x144 + tile color) -->
    <meta name="msapplication-TileImage" content="assets/images/touch/ms-touch-icon-144x144-precomposed.png">
    <meta name="msapplication-TileColor" content="#3372DF">

    <link rel="shortcut icon" href="assets/images/favicon.png">

    <!-- SEO: If your mobile URL is different from the desktop URL, add a canonical link to the desktop page https://developers.google.com/webmasters/smartphone-sites/feature-phones -->
    <!--
    <link rel="canonical" href="http://www.example.com/">
    -->
    <script src="http://code.jquery.com/jquery-2.1.4.min.js"></script>
    <link rel="stylesheet" href="assets/font-awesome/css/font-awesome.min.css" />
    <script src="assets/js/events.js"></script>

    <link rel="stylesheet" href="assets/css/normalize.css" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:regular,bold,italic,thin,light,bolditalic,black,medium&amp;lang=en">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://code.getmdl.io/1.3.0/material.grey-orange.min.css">
    <link rel="stylesheet" href="assets/css/styles.css">
    <link rel="stylesheet" href="assets/css/style.css">

</head>
<body>

<main id="admin">
  <nav>
      <a href="index.php?page=admin&tab=add">Add Post</a>

      <a href="index.php?page=admin&tab=user">Users</a>
  </nav>

    <table class="standard-table">
        <caption>Les posts</caption>
        <thead>
        <tr>
            <th>Posts ID</th>
            <th>Date de creation</th>
            <th >Title</th>

            <th >Categorie</th>
            <th>delete</th>
            <th>edite</th>

        </tr>
        </thead>
        <tbody>
        <?php foreach ($aPosts as $iIndex => $aCols) {
            ?>
            <tr>
                <td><?=$aCols['id']?></td>
                <td><?= $aCols['posts_date']; ?></td>

                <td ><?= $aCols['posts_title']; ?></td>

                <td ><?= $aCols['tag']; ?></td>
               
                   <td ><a href="" data-id="<?=$aCols['id']?>" class="del"><i class="fa fa-trash" aria-hidden="true"></i></a></td>
             
                <td ><a href="index.php?page=admin&tab=edit&id=<?=$aCols['id']?>"><i class="fa fa-pencil" aria-hidden="true"></a></td>
            </tr>
        <?php } ?>
        </tbody>

    </table>
</main>




<script src="https://code.getmdl.io/1.3.0/material.min.js"></script>
<script src="assets/js/main.js"></script>
</body>

<script>
    Array.prototype.forEach.call(document.querySelectorAll('.mdl-card__media'), function(el) {
        var link = el.querySelector('a');
        if(!link) {
            return;
        }
        var target = link.getAttribute('href');
        if(!target) {
            return;
        }
        el.addEventListener('click', function() {
            location.href = target;
        });
    });
</script>
</html>
